# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: b9936b5d0cee42e899c64a2bb176f59c94bb76b3f3e55fa77f0aa72faa127e1b4b230a7a33df33d87eea773dfb1528f4ca9b9e961ac73413d52cf954274e1cfd

test:
  secret_key_base: ee553a6d73fb77d4ad3a9d04d762605efc4b2b8df925aa396386b63093916154cc999684d97dd424ad09ebb0a55f4f80419c6dcfee8809af164f1995c95312a4

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
